//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Diagnostics.SymbolStore;

namespace CoffeShop.Models
{
    using System;
    using System.Collections.Generic;

    // fileupload iþlemi için eklemesi gereken kütüphaneler 
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    using System.Web.Mvc;
    public partial class hakkimizda
    {
        public int ID { get; set; }


        public string Foto { get; set; }
        public virtual HttpPostedFileBase fotoFile { get; set; }


        [Required]
        [Display(Name = "Baþlýk")]
        public string Baslik { get; set; }

        [Required]
        [Display(Name = "Üst Baþlýk")]
        public string UstBaslik { get; set; }


        [AllowHtml]
        [Required]
        [Display(Name = "Ýçerik")]
        public string Icerik { get; set; }
    }
}
