//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace CoffeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanicilar
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "Lütfen Kullanýcý Adýný Giriniz!.")]
        public string KullaniciAdi { get; set; }

        [Required(ErrorMessage = "Lütfen Kullanýcý Parolanýzý Giriniz!.")]
        public string Sifre { get; set; }
        public Nullable<sbyte> AdminRole { get; set; }


        public virtual bool BeniHatirla { get; set; }
    }
}
