//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeShop.Models
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel.DataAnnotations;
    using System.Web;
    using System.Web.Mvc;

    public partial class urunler
    {
        public int ID { get; set; }

        public string UrunFoto { get; set; }
        public virtual HttpPostedFileBase fotoFile { get; set; }

        [Required]
        [Display(Name = "Ürün Baþlýk")]
        public string UrunBaslik { get; set; }

        [Required]
        [Display(Name = "Ürün Üst Baþlýk")]
        public string UrunUstBaslik { get; set; }

        [Required]
        [Display(Name = "Ürün Ýçerik")]
        [AllowHtml]
        public string Icerik { get; set; }

        public bool UrunDurum { get; set; }

        [Required]
        [Display(Name = "Ürün Sýra")]
        public Nullable<int> UrunSira { get; set; }
    }
}
